# Generated by Django 5.1.1 on 2024-09-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
